version: '3.6'

services:
  app:
    image: node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    stdin_open: true
    command: bash

networks:
  default:
    external:
      name: wizard-react-test